# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "All iOS lanes"
  lane :all_checks do
    sh("mkdir -p ../sonar-reports/iOS")
    sync_code_signing(type: "development", readonly: true, platform: "ios")
    lint
    run_all_test_ios
    coverage_ios
  end

  desc "Run all test for iOS modules"
  lane :run_all_test_ios do
    run_tests(
      project: "Accounts.xcodeproj",
      scheme: "Accounts (iOS)",
      sdk: "iphonesimulator14.5",
      device: "iPhone 8 (14.5)",
      output_directory: "sonar-reports/iOS",
      clean: true,
    )
  end

  desc "Calculate the code coverage for iOS packages"
  lane :coverage_ios do
    slather(
      scheme: "Accounts (iOS)",
      proj: "Accounts.xcodeproj",
      output_directory: "sonar-reports/iOS",
      cobertura_xml: "true",
      sonarqube_xml: true,
      cobertura_xml: false,
      ignore: [
        "*/Package.swift",
        "DerivedData/*",
        "*/Tests/*"
      ],
    )
  end

  desc "Lint all files"
  lane :lint do
    swiftlint(
      output_file: "sonar-reports/Accounts-macOS-swiftlint.txt",
      ignore_exit_status: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Accounts (iOS)")
    upload_to_testflight
  end
end

platform :mac do

  desc "All macOS lanes"
  lane :all_checks do
    sh("mkdir -p ../sonar-reports/macOS")
    sync_code_signing(type: "development", readonly: true, platform: "macos")
    lint
    run_all_test_macos
    coverage_macos
  end

  desc "Run all test for macOS modules"
  lane :run_all_test_macos do
    run_tests(
      project: "Accounts.xcodeproj",
      scheme: "Accounts (macOS)",
      destination: "'platform=macOS, arch=x86_64'",
      output_directory: "sonar-reports/macOS",
      clean: true,
    )
  end

  desc "Calculate the code coverage for macOS packages"
  lane :coverage_macos do
    slather(
      scheme: "Accounts (macOS)",
      proj: "Accounts.xcodeproj",
      output_directory: "sonar-reports/macOS",
      cobertura_xml: "true",
      sonarqube_xml: true,
      cobertura_xml: false,
      ignore: [
        "*/Package.swift",
        "DerivedData/*",
        "*/Tests/*"
      ],
    )
  end

  desc "Lint all files"
  lane :lint do
    swiftlint(
      output_file: "sonar-reports/Accounts-macOS-swiftlint.txt",
      ignore_exit_status: true
    )
  end
end

